export const CREATE_CANTEEN_REQUEST = "CREATE_CANTEEN_REQUEST";
export const CREATE_CANTEEN_SUCCESS = "CREATE_CANTEEN_SUCCESS";
export const CREATE_CANTEEN_FAILURE = "CREATE_CANTEEN_FAILURE";

export const GET_ALL_CANTEEN_REQUEST = "GET_ALL_CANTEEN_REQUEST";
export const GET_ALL_CANTEEN_SUCCESS = "GET_ALL_CANTEEN_SUCCESS";
export const GET_ALL_CANTEEN_FAILURE = "GET_ALL_CANTEEN_FAILURE";

export const DELETE_CANTEEN_REQUEST = "DELETE_CANTEEN_REQUEST";
export const DELETE_CANTEEN_SUCCESS = "DELETE_CANTEEN_SUCCESS";
export const DELETE_CANTEEN_FAILURE = "DELETE_CANTEEN_FAILURE";

export const UPDATE_CANTEEN_REQUEST = "UPDATE_CANTEEN_REQUEST";
export const UPDATE_CANTEEN_SUCCESS = "UPDATE_CANTEEN_SUCCESS";
export const UPDATE_CANTEEN_FAILURE = "UPDATE_CANTEEN_FAILURE";

export const UPDATE_CANTEEN_STATUS_REQUEST = "UPDATE_CANTEEN_STATUS_REQUEST";
export const UPDATE_CANTEEN_STATUS_SUCCESS = "UPDATE_CANTEEN_STATUS_SUCCESS";
export const UPDATE_CANTEEN_STATUS_FAILURE = "UPDATE_CANTEEN_STATUS_FAILURE";

export const GET_CANTEEN_BY_USER_ID_REQUEST = "GET_CANTEEN_BY_USER_ID_REQUEST";
export const GET_CANTEEN_BY_USER_ID_SUCCESS = "GET_CANTEEN_BY_USER_ID_SUCCESS";
export const GET_CANTEEN_BY_USER_ID_FAILURE = "GET_CANTEEN_BY_USER_ID_FAILURE";

export const CREATE_CATEGORY_REQUEST = "CREATE_CATEGORY_REQUEST";
export const CREATE_CATEGORY_SUCCESS = "CREATE_CATEGORY_SUCCESS";
export const CREATE_CATEGORY_FAILURE = "CREATE_CATEGORY_FAILURE";

export const GET_CANTEEN_CATEGORY_REQUEST = "GET_CANTEEN_CATEGORY_REQUEST";
export const GET_CANTEEN_CATEGORY_SUCCESS = "GET_CANTEEN_CATEGORY_SUCCESS";
export const GET_CANTEEN_CATEGORY_FAILURE = "GET_CANTEEN_CATEGORY_FAILURE";